services:
  - type: web
    name: kiosk-suvidha-backend
    env: node
    plan: free
    buildCommand: NODE_OPTIONS="--max-old-space-size=4096" npm install && npx prisma generate && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kiosk-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://kiosk-suvidha.vercel.app

databases:
  - name: kiosk-db
    plan: free
    postgresMajorVersion: 15
